### ISSUE TITLE
How can I make a same one?

### ISSUE THREAD

**Issue by Er-hgy** [AmineLAHRIM/MarrakechTour-Guide#1]
The website is so beautiful that I want to make a same one to introduce my hometown using Wordpress, can you tell me how can I realize it?

**Comment by AmineLAHRIM** [comment]
Hi Er-hgy,

i can create one for you with your image and everything’s
here my link of upwork
https://www.upwork.com/freelancers/~017279704e226273e9 <https://www.upwork.com/freelancers/~017279704e226273e9>

Best Regards Amine
